apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: examples
spec:
  owner: JioDigitalU2CDevTeam
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jio-developer-portal
spec:
  type: service
  lifecycle: dev
  owner: group:JioDigitalU2CDevTeam
  system: examples
  providesApis: [digital-balance-adjustment]
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: digital-balance-adjustment
  description: Digital Balance Adjustment upgrade of plan offering with redemption of value for an existing plan offering
spec:
  type: openapi
  lifecycle: dev
  owner: JioDigitalU2CDevTeam
  system: examples
  definition: ./digital-balance-adjustment.json
