apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: digital-balance-adjustment
  description: Digital Balance Adjustment upgrade of plan offering with redemption of value for an existing plan offering
spec:
  type: openapi
  lifecycle: dev
  owner: JioDigitalU2CDevTeam
  system: examples
  definition:
    $text: 'https://gist.githubusercontent.com/lenage/08964335de9064540c8c335fb849c5da/raw/6d63e3546897356882ed7e30cd48891a24e2b354/feature.swagger.json'
