apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: digital-balance-adjustment
  description: Digital Balance Adjustment upgrade of plan offering with redemption of value for an existing plan offering
spec:
  type: openapi
  lifecycle: dev
  owner: JioDigitalU2CDevTeam
  system: examples
  definition:
    $text: ./digital-balance-adjustment.json
